name: todo
description: A simple Todo list with ♥ flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.3
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  loading_animation_widget: ^1.2.0+2
  table_calendar: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true
  fonts:
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PTSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/PTSans-Italic.ttf
  assets:
    - assets/images/logo.svg