name: todo
description: A simple Todo list with ♥ flutter.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.7.1
  flutter_svg: ^1.1.3
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+2
  path_provider: ^2.0.11
  table_calendar: ^3.0.6
  timezone: ^0.8.0
  share_plus: ^4.1.0
  
dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true
  assets:
    - assets/images/logo.svg
